### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by mdjastrzebski** [callstack/brownfield-ref#1]
## Project Roadmap

- [ ] Create a simple iOS app (list + details screen) using modern practices
- [x] Create a simple Android app (list + details screen) using modern practices
- [ ] Add iOS brownfield setup
- [ ] Add Android brownfield setup
